# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-oaMYZfs3xuRWVzRITtzzPzzMyb_5rRO
"""

#Funcion que retorna la suma de dos numeros
def sumar(a,b):
  return a + b

x = int(input("ingrese el primer numero: "))
y = int(input("Ingrese el segundo numero: "))
print("La suma es: ", sumar(x,y))

def multiplicar(b,h):
  return b * h
x = int(input("Ingrese la medida de la base del rectangulo: "))
y = int(input("Ingrese la medida de la altura del rectangulo: "))
print("El area del rectangulo es: ", multiplicar(x,y))